# Generated by Django 4.0.3 on 2022-04-21 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MascotasApp', '0005_mascota_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='apellido')),
                ('edad', models.PositiveIntegerField(default=0)),
                ('email', models.CharField(max_length=150, verbose_name='email')),
                ('numero', models.PositiveIntegerField(default=0)),
                ('domicilio', models.CharField(max_length=500, verbose_name='domicilio')),
                ('razon_para_adoptar', models.CharField(max_length=100000, verbose_name='razon_para_adoptar')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MascotasApp.mascota')),
            ],
            options={
                'verbose_name': 'adopcion',
                'verbose_name_plural': 'adopciones',
                'db_table': 'adopcion',
                'ordering': ['id'],
            },
        ),
    ]
