# Generated by Django 4.0.3 on 2022-04-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MascotasApp', '0005_mascota_descripcion'),
        ('AdopcionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='mascota',
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MascotasApp.mascota'),
        ),
    ]
