# Generated by Django 4.0.3 on 2022-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionApp', '0002_remove_adopcion_mascota_alter_adopcion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='usuario',
            field=models.CharField(default=0, max_length=150, verbose_name='nombre'),
            preserve_default=False,
        ),
    ]
