# Generated by Django 4.0.3 on 2022-04-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionApp', '0003_adopcion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='nombre',
        ),
    ]
