# Generated by Django 4.0.3 on 2022-04-21 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MascotasApp', '0005_mascota_descripcion'),
        ('AdopcionApp', '0004_remove_adopcion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='mascota',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MascotasApp.mascota'),
            preserve_default=False,
        ),
    ]
