# Generated by Django 4.0.3 on 2022-04-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionApp', '0005_adopcion_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopcion',
            old_name='usuario',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='mascota',
            field=models.CharField(max_length=150, verbose_name='mascota'),
        ),
    ]
