# Generated by Django 4.0.3 on 2022-05-11 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionApp', '0007_adopcion_fecha_rescate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='fecha_rescate',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='fecha_solicitud',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha_solicitud'),
        ),
    ]
