# Generated by Django 4.0.3 on 2022-04-16 23:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
                ('numero', models.PositiveIntegerField(default=0)),
                ('dpi', models.CharField(max_length=10, unique=True, verbose_name='dpi')),
                ('fecha_registro', models.DateField(default=datetime.datetime.now, verbose_name='fecha_registro')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/%Y/%M/%D')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugioapp.type')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
