# Generated by Django 4.0.3 on 2022-04-17 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MascotasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotomascota/%Y/%M/%D')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MascotasApp.mascota')),
            ],
        ),
    ]
