# Generated by Django 4.0.3 on 2022-04-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascotasApp', '0004_alter_mascota_enfermedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.CharField(default=0, max_length=50000, unique=True, verbose_name='descripcion'),
            preserve_default=False,
        ),
    ]
