# Generated by Django 4.0.3 on 2022-05-10 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MascotasApp', '0005_mascota_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoptado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'adoptado',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='id_mascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='alimentacion',
            field=models.CharField(default=5, max_length=150, verbose_name='alimentacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacunas',
            field=models.CharField(default=0, max_length=20, verbose_name='vacuna'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.CharField(max_length=150, unique=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='adoptado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MascotasApp.adoptado'),
            preserve_default=False,
        ),
    ]
