# Generated by Django 4.0.3 on 2022-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascotasApp', '0006_adoptado_remove_mascota_id_mascota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default=0, max_length=20, verbose_name='raza'),
            preserve_default=False,
        ),
    ]
